language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter || true
addons:
  code_climate:
    repo_token: 5dcf014e3a26ded8ffe8ff8bc70f98d49523e4851613123d8359035d44937953
